title: Controlook - Sistema Online de Gestão para Igrejas
email: contato@controlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Controlook é um sistema online para organizar sua igreja
  com uma eficaz gestão financeira e controle dos membros
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://controlook.com" # the base hostname & protocol for your site, e.g. http://example.com
url_signup: "https://sys.controlook.com/signup/"
url_login: "https://sys.controlook.com"
twitter_username: controlook
github_username: controlook
instagram_username: controlook
facebook_username: controlook

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gruntfile.js
  - node_modules
  - package-lock.json
  - package.json
  - run.sh
  - scss
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
